---
- name: Run database setup
  shell:
    cmd: |
      pgcli -h localhost -p 5432 -U postgres >/dev/null <<EOF
      \i data/1.0/1_users.sql
      \i data/1.0/2_roles.sql
      \i data/1.0/3_rel_users_roles.sql
      EOF
  args:
    chdir: "{{ plantd_master_srcdir }}"
  tags: [ "plantd-master" ]
