---
# Variable configuration
- include_tasks: variables.yml

# Setup/install tasks
- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: build.yml
- include_tasks: initialize.yml

# TODO: - include_tasks: configure.yml
# TODO: - import_tasks: users.yml

#- name: Ensure Plantd Master is started and enabled on boot.
#  systemd:
#    name: "{{ plantd_master_daemon }}"
#    state: "{{ plantd_master_service_state }}"
#    enabled: "{{ plantd_master_service_enabled }}"
#    daemon_reload: yes
#  tags: [ "plantd-master" ]
