---
# Variable configuration
- include_tasks: variables.yml

# Setup/install tasks
- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

#- include_tasks: initialize.yml
#- include_tasks: configure.yml

- name: Ensure Plantd Master is started and enabled on boot.
  service:
    name: "{{ plantd_master_daemon }}"
    state: "{{ plantd_master_service_state }}"
    enabled: "{{ plantd_master_service_enabled }}"

# Configure Plantd Master
#- import_tasks: databases.yml
#- import_tasks: users.yml
