---
- name: restart plantd-master
  systemd:
    name: "{{ plantd_master_daemon }}"
    state: "{{ plantd_master_restarted_state }}"
    enabled: "{{ plantd_master_service_enabled }}"
    daemon_reload: yes
  tags: [ "plantd-master" ]
